### ISSUE TITLE
Prettier doesn't work anymore on Vue files

### ISSUE THREAD

**Issue by bokub** [simonhaenisch/prettier-plugin-organize-imports#16] opened 2021-04-14 08:02 UTC
Hi,
I installed your plugin on my Vue.js project.

When running prettier on my project (`npx prettier -w .`), it changed the order of imports if several Typescript files (as expected), but not any .vue files.

I though "The plugin is not working on Vue files, but it's not a big deal"

But then I noticed that Prettier **completely stopped working** on Vue files ! Running prettier doesn't throw any error, it just acts like my Vue files are correctly formatted (even if they are not).

Is it expected?
Thanks

**Comment by simonhaenisch** [comment] 2021-04-14 15:44
Hi, thanks for the issue report. I'm not sure why this would be happening. There's not much going on with this plugin, it just registers itself as a preprocessor within the typescript parsers:

https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/120c88b58e0d751958a2e5bb3f0dac1a31221d4a/index.js#L91-L98

I don't really have time to look into this right now but maybe you can find out whether `.vue` files are processed by the typescript parser in Prettier?

**Comment by bokub** [comment] 2021-04-14 15:45
All right, I'll investigate and tell you what I can find 👍

**Comment by simonhaenisch** [comment] 2021-04-15 07:37
I just tried creating an empty project, installed `prettier`, `prettier-plugin-organize-imports` and `typescript`, then created a `.vue` file with a simple component and an import statement, and Prettier runs just fine 🤷🏻‍♂️

Just had a quick look at https://vuejs.org/v2/guide/typescript.html, is this what you're using? Anyway, since I'm unable to reproduce and don't have much Vue knowledge, I'll just leave this open for you to investigate and keep us updated.

**Comment by bokub** [comment] 2021-04-15 07:46
In a vue component, you can use both JavaScript and TypeScript, and prettier knows how to handle both of them.

In my case, yes, I was using TypeScript (`<script lang="ts"></script>`).

I'll do my own tests and I'll tell you what I can find!

**Comment by simonhaenisch** [comment] 2021-05-06 08:22
Closing this for now because it's not actionable with the current information. If you find out more or can provide a reproducible example, I'll reopen.

**Comment by Shinigami92** [comment] 2021-05-17 14:03
Here is a repro: https://github.com/Shinigami92/prettier-repro-10905
Please re-open it

I opened an issue here before: https://github.com/prettier/prettier/issues/10905

**Comment by simonhaenisch** [comment] 2021-05-17 19:13
So i've done some investigating, and the whole situation is a bit confusing:

- `organizeImports` (or "Organize Imports" action in VS Code) doesn't actually work on Vue files. So what's the point of installing this plugin in a Vue project?
- For whatever reason `.vue` files go through the `typescript` parser's preprocessor, even when you explicitly set `parser: 'vue'` in the config that is passed to `prettier.format`.
- The preprocessor throws `Error: Could not find source file: 'App.vue'.` but I didn't add any error handling.
- When the preprocessor throws, Prettier doesn't format the file but also doesn't throw an error, it just swallows it up.

This does not make much sense to me but I'll release a fix with a `try/catch` around the import organizing.

Just wondering, why would you install this plugin in a Vue project? Is there a mix of Vue and TypeScript files, or were you expecting this plugin to work for `.vue` files?

**Comment by Shinigami92** [comment] 2021-05-17 19:36
The code between `<script lang="ts">` and `</script>` is totally valid normal TypeScript and also has totally normal valid imports. When I move all the code between those `script` segments to a `.ts` file, the imports get organized by your plugin.

**Comment by simonhaenisch** [comment] 2021-05-17 19:55
Ok I see, I didn't have the Vetur extension installed, so the "Organize Imports" action didn't even come up.

So I assume prettier does something similar with the different language contexts, and that's why the TypeScript parser is invoked. I've managed to get this to work by giving TypeScript a wrong file name. I'll make this specific to `.vue` files.

**Comment by simonhaenisch** [comment] 2021-05-17 20:10
Released `2.1.0` to npm just now, please give it a try and let me know if it doesn't work (:

Thanks for taking the time to make the repro, very helpful!

**Closed by simonhaenisch** 2021-05-17 20:10 UTC
Labels: bug

**Comment by Shinigami92** [comment] 2021-05-17 20:19
It works, but it removes some intended blank lines :eyes: ?!

e.g. 

```vue
<template lang="pug">
prism(language='typescript') {{ current.sourceText }}
</template>

<script lang="ts">
import { defineComponent, ref, Ref } from 'vue';
import Prism from 'vue-prism-component';
import { fileName, sourceText } from './greeter-example';

export default defineComponent({
  components: {
    Prism
  },
  setup() {
    const current: Ref<{ fileName: string; sourceText: string }> = ref({ fileName, sourceText });

    return { current };
  }
});
</script>
```

becomes
```vue
<template lang="pug">
prism(language='typescript') {{ current.sourceText }}
</template>

<script lang="ts">
import { defineComponent, ref, Ref } from 'vue';
import Prism from 'vue-prism-component';
import { fileName, sourceText } from './greeter-example';
export default defineComponent({
  components: {
    Prism
  },
  setup() {
    const current: Ref<{ fileName: string; sourceText: string }> = ref({ fileName, sourceText });
    return { current };
  }
});
</script>
```

But I like to have a blank line between imports and the code
And a blank line above the `return` statement

**Comment by Shinigami92** [comment] 2021-05-17 20:24
I think it may have something to do with this line 

https://github.com/simonhaenisch/prettier-plugin-organize-imports/compare/v2.0.0...v2.1.0#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R30

**Comment by simonhaenisch** [comment] 2021-05-18 07:02
That link doesn't work, can you get a permalink from https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/v2.1.0/index.js? I've noticed a similar thing in `.tsx` files once though, that it would remove blank lines but only inside jsx templates. I thought it was a change in prettier but maybe not.

**Comment by Shinigami92** [comment] 2021-05-18 07:08
https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/c997a23ccab3877fe07cede13736af7e0d8530f1/index.js#L30

**Comment by bokub** [comment] 2021-05-18 08:38
Thanks @Shinigami92 for taking over this issue! I didn't have the time to do it myself

And of course, thanks @simonhaenisch for fixing it :+1:
