### ISSUE TITLE
Does not work with pug templates via VS Code Prettier plugin

### ISSUE THREAD

**Issue by Shinigami92** [simonhaenisch/prettier-plugin-organize-imports#84] opened 2022-11-14 08:26 UTC
Now #78 is solved and `prettier --write .` works... But when I run format on save via VSCode it is the same behavior as before #78 got fixed 🤔 

But now I'm not sure if this has something todo with your plugin or if [esbenp.prettier-vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) has a bug.
I highly assume it has still something todo with the `vueCompilerOptions` not forwarded correctly.

/ping @johnsoncodehk

**Comment by Shinigami92** [comment] 2022-11-14 08:29
I need to find some time to dig deeper into this, for now I set `organizeImportsSkipDestructiveCodeActions: true` so I can work

**Comment by simonhaenisch** [comment] 2022-11-14 10:29
Have you tried restarting VS Code or reloading the project? 😅

**Comment by Shinigami92** [comment] 2022-11-14 10:33
Yes, even days passed since I discovered it, but today it's my first day I actually **work** with the new version at company.

I can reproduce this in multiple projects.

**Comment by simonhaenisch** [comment] 2022-11-14 10:36
Could you share some more details about your VS Code config and possibly workspace config? At least all the settings related to `prettier` and format-on-save/code-actions-on-save, and maybe whether your project using VS Code's built-in `typescript` or the one installed into your project.

**Comment by Shinigami92** [comment] 2022-11-14 10:48
Checkout https://github.com/Shinigami92/prettier-plugin-organize-imports-issue-78, install deps and go to `src/App.vue` and save the file e.g. with `CMD + S` on MacOS

**Comment by simonhaenisch** [comment] 2022-11-14 11:20
Ok can reproduce, and the first difference I can tell (from logging some stuff into VS Code developer tools) is that when run from the CLI, it runs in the path relative to the project, whereas the VS Code Prettier extension runs the project from the system root (i.e. `process.cwd()` gives `/`) 😳 That might cause an issue with finding the tsconfig but i'll dig some deeper to narrow it down.

**Comment by simonhaenisch** [comment] 2022-11-14 11:31
So, it finds the tsconfig and Vue compiler options just fine, however Volar fails to load the pug language plugin:

```
[Extension Host] Load plugin failed @volar/vue-language-plugin-pug Error: Cannot find module '@volar/vue-language-plugin-pug'
Require stack:
- /path/to/prettier-plugin-organize-imports-issue-78/node_modules/@volar/vue-language-core/out/plugins.js
- /path/to/prettier-plugin-organize-imports-issue-78/node_modules/@volar/vue-language-core/out/languageModule.js
- /path/to/prettier-plugin-organize-imports-issue-78/node_modules/@volar/vue-language-core/out/index.js
- /path/to/prettier-plugin-organize-imports-issue-78/node_modules/@volar/vue-typescript/out/index.js
- /path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier-plugin-organize-imports/lib/get-language-service.js
- /path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier-plugin-organize-imports/lib/organize.js
- /path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier-plugin-organize-imports/index.js
- /path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier/index.js
- /user-dir/.vscode/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Function.p.resolve (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:761)
    at getDefaultVueLanguagePlugins (/path/to/prettier-plugin-organize-imports-issue-78/node_modules/@volar/vue-language-core/out/plugins.js:33:44)
    at Object.createLanguageModule (/path/to/prettier-plugin-organize-imports-issue-78/node_modules/@volar/vue-language-core/out/languageModule.js:10:74)
    at Object.createLanguageService (/path/to/prettier-plugin-organize-imports-issue-78/node_modules/@volar/vue-typescript/out/index.js:6:23)
    at getLanguageService (/path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier-plugin-organize-imports/lib/get-language-service.js:14:43)
    at module.exports.organize (/path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier-plugin-organize-imports/lib/organize.js:26:26)
    at organizeImports (/path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier-plugin-organize-imports/index.js:19:10)
    at Object.preprocess (/path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier-plugin-organize-imports/index.js:42:4)
    at Object.parse (/path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier/index.js:7330:25)
    at coreFormat (/path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier/index.js:8645:18)
    at formatWithCursor2 (/path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier/index.js:8837:18)
    at /path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier/index.js:37229:12
    at Object.format (/path/to/prettier-plugin-organize-imports-issue-78/node_modules/prettier/index.js:37243:12)
    at t.default.format (/user-dir/.vscode/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js:1:14565)
    at t.PrettierEditProvider.provideEdits (/user-dir/.vscode/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js:1:11259)
    at B.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:45902)
```

Not sure why this happens, all the paths look kinda ok 🤷🏻‍♂️ Maybe @johnsoncodehk has an idea...

**Comment by johnsoncodehk** [comment] 2022-11-14 11:42
I can't reproduce this problem, I just try install [esbenp.prettier-vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and save App.vue but no luck.

Can you try log `rootDir` at node_modules/@volar/vue-language-core/out/plugins.js line 33?

**Comment by Shinigami92** [comment] 2022-11-14 11:44
@johnsoncodehk Did you configure to run formatOnSave with the plugin? VSCode ships it's own formatter by default which is !=prettier.ext

**Comment by simonhaenisch** [comment] 2022-11-14 13:07
> Can you try logging `rootDir`

@johnsoncodehk I get `"/"`.

**Comment by Shinigami92** [comment] 2022-11-14 14:55
So can you release a bug fix version for that? Or did I misunderstood you?

**Comment by simonhaenisch** [comment] 2022-11-14 18:59
No, I don't think I can fix anything, the problem is that `@volar/vue-language-core` can't locate `@volar/vue-language-plugin-pug` because it has the wrong root path, which I assume is because the Prettier VS Code extension does something like `cd / && prettier --write /path/to/project` instead of `cd /path/to/project && prettier --write .` (not sure though, just my first guess).

I guess it could potentially get fixed in `@volar/vue-language-core` to somehow determine the project's root path differently for finding the Vue compiler plugins. However I'm not sure it's the correct approach, because to me it seems kinda incorrect how the Prettier plugin runs `prettier`... why would it not run it in a way that the current VS Code project path is the cwd but rather `/` 🤷🏻‍♂️ (maybe because of multi-root projects?)

Or maybe I need to do something differently when creating the Vue language service, e. g. override the `getCurrentDirectory` method of the LS host? Only possible solution I can think of is to do sth like

```ts
getCurrentDirectory() {
  return path.relative(tsconfigPath, filepath)
}
```

which I guess I could give a try but not sure it makes sense, or whether it could potentially break other stuff.

**Comment by simonhaenisch** [comment] 2022-11-14 19:19
Update: yeah ok this seems to make it work:

```ts
getCurrentDirectory() {
  return path.dirname(tsconfig)
}
```

**Comment by Shinigami92** [comment] 2022-11-14 19:21
> (I'd only add this to the Vue language service host)

I think this is okay, as only .vue files are affected (I assume)

**Comment by Shinigami92** [comment] 2022-11-14 20:45
If possible for you, just release a test version for me and I will test it out tomorrow
Or alternatively, tell me what I could change temporarily in my node_modules to test it

**Comment by simonhaenisch** [comment] 2022-11-15 10:01
To test it out, can you create a file `patches/prettier-plugin-organize-imports+3.2.0.patch` in your project, with the following content:

```patch
diff --git a/node_modules/prettier-plugin-organize-imports/lib/get-compiler-options.js b/node_modules/prettier-plugin-organize-imports/lib/get-compiler-options.js
index e7b97cf..f67a466 100644
--- a/node_modules/prettier-plugin-organize-imports/lib/get-compiler-options.js
+++ b/node_modules/prettier-plugin-organize-imports/lib/get-compiler-options.js
@@ -49,3 +49,5 @@ module.exports.getVueCompilerOptions = memoize(getVueCompilerOptions);
  * @type {(path: string) => string | undefined}
  */
 const findTsconfig = memoize((path) => ts.findConfigFile(path, ts.sys.fileExists));
+
+module.exports.findTsconfig = findTsconfig;
diff --git a/node_modules/prettier-plugin-organize-imports/lib/service-host.js b/node_modules/prettier-plugin-organize-imports/lib/service-host.js
index 9dbc3ab..ab2c63b 100644
--- a/node_modules/prettier-plugin-organize-imports/lib/service-host.js
+++ b/node_modules/prettier-plugin-organize-imports/lib/service-host.js
@@ -1,6 +1,7 @@
+const { dirname } = require('path');
 const ts = require('typescript');
 
-const { getCompilerOptions, getVueCompilerOptions } = require('./get-compiler-options');
+const { findTsconfig, getCompilerOptions, getVueCompilerOptions } = require('./get-compiler-options');
 
 /**
  * Create the most basic TS language service host for the given file to make import sorting work.
@@ -45,6 +46,7 @@ function getTypeScriptLanguageServiceHost(path, content) {
  */
 function getVueLanguageServiceHost(path, content) {
 	const vueCompilerOptions = getVueCompilerOptions(path);
+	const tsconfig = findTsconfig(path);
 
 	return {
 		...getTypeScriptLanguageServiceHost(path, content),
@@ -57,6 +59,7 @@ function getVueLanguageServiceHost(path, content) {
 		 * @returns {any}
 		 */
 		getTypeScriptModule: () => ts,
+		getCurrentDirectory: () => dirname(tsconfig),
 	};
 }
 
```

and then run `npx patch-package` to apply this.

**Comment by simonhaenisch** [comment] 2022-11-15 10:17
Main issue I have with doing this "fix": it's overriding the default implementation (`ts.sys.getCurrentDirectory`) and I'm not super familiar with the language service host API, so I'm really not sure what other implications this change might have... e.g. maybe the dir containing the tsconfig wouldn't/shouldn't always be the cwd?

Just looked up the default implementation and it just returns `process.cwd()` btw ([link](https://github.com/microsoft/TypeScript/blob/343191217575c20e2ee7845927d5ca23981cc663/src/compiler/sys.ts#L1474)).

Still not convinced the Prettier VS Code extension is doing the right thing by running the `prettier` process from `/` (system root), but not sure it can be changed 🤷🏻‍♂️

Anyway, @johnsoncodehk: I would appreciate some input if you think this should be fixed via `getCurrentDirectory` in the language service host implementation, or whether it's actually Volar's job to find the project's correct root directory if it's not the same as `process.cwd()`? As I said I'm not sure what the purpose of `getCurrentDirectory` is: return the dir that the process is running from, or return the project root? From the method's name I would rather thing the former 🤷🏻‍♂️

**Comment by johnsoncodehk** [comment] 2022-11-15 10:45
@simonhaenisch Overriding `getCurrentDirectory` is the correct way as I know, please do it, thanks for your investigation! `process.cwd()` should return workspace root in the language server by default, not sure why it doesn't somehow.

Please know that, for multiple roots workspace, you should create multiple TS language service instances with provide different `getCurrentDirectory`.

**Comment by Shinigami92** [comment] 2022-11-15 13:31
> https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/84#issuecomment-1315070974

Tested, works 👍

**Comment by simonhaenisch** [comment] 2022-11-15 13:34
Ok then I guess I'll implement this as a fix and hope it doesn't backfire 🤞😅 Might take a couple days though.

**Comment by Shinigami92** [comment] 2022-11-21 09:24
@simonhaenisch what's the state?

**Comment by simonhaenisch** [comment] 2022-11-24 14:16
Sorry I was sick, will need a bit longer for this one.

**Comment by Shinigami92** [comment] 2022-11-24 15:54
> Sorry I was sick, will need a bit longer for this one.

Get well soon, I depend on you ^^

**Closed** 2022-11-25 14:12 UTC

**Comment by simonhaenisch** [comment] 2022-11-25 14:21
@Shinigami92 finally got around to finish this, should work in `3.2.1` 🤞

**Comment by Shinigami92** [comment] 2022-11-25 14:44
> @Shinigami92 finally got around to finish this, should work in `3.2.1` crossed_fingers

Thanks, might be that I can test it first on monday

**Comment by Shinigami92** [comment] 2022-11-28 08:11
@simonhaenisch Works 🙆
