### ISSUE TITLE
Inconsistency after 3.0.2

### ISSUE THREAD

**Issue by blaenk** [simonhaenisch/prettier-plugin-organize-imports#73] opened 2022-08-28 03:53 UTC
Sorry for the vague title. This took me a while to track down.

I was using `prettier-plugin-organize-imports` at `3.1.0` and noticing that prettier wasn't organizing my imports. I ignored it though since it wasn't a big deal but then github actions failed because somehow it worked there and so my eslint check failed.

I had no idea if it was this plugin or something else, but just now I got to the point of downgrading and I had to go all the way back to `3.0.2` for it to work.

I have a hunch that this is specific to Windows which I am currently on, and would explain why on github actions (ubuntu) it worked fine despite getting the same version of the package afaik (used `yarn install --immutable`).

The behavior I'm observing is that if I run e.g. `yarn run prettier --list-different .` at the root of the package, it doesn't detect any discrepancies. If I run it in the subdirectory actually containing the file with discrepancies (i.e. deviations from prettier formatting, specifically unused imports), then it does indeed detect it, both with `.` and with `File.tsx` directly.

Sorry if that report is vague. I'm happy to provide any other information you may need to figure this out. For now I will be using 3.0.2.

Thank you so much for working on this great plugin!

**Comment by simonhaenisch** [comment] 2022-08-29 10:36
Hm this is weird, there's only a performance regression in `3.0.2` that was fixed in `3.0.3`, see [v3.0.2..v3.0.3](https://github.com/simonhaenisch/prettier-plugin-organize-imports/compare/v3.0.2..v3.0.3).

`3.1.0` just adds a new option to skip destructive code actions but that didn't change any of the code (or at least i don't think so). Since you're saying you had to go back to `3.0.2`, I assume the problem is happening with `3.0.3`? So I'd say the above link is what breaks it for you then, just not sure why 🤷🏻‍♂️ Sorry can't really help you debug this further unless you can provide some reproducible example somewhere (stackblitz or so).

**Comment by AaronSterlingGENEICD** [comment] 2022-08-30 13:41
I can confirm this. v3.0.2 works when run from Windows cmd.exe. Later versions work when run from Linux, but not from Windows,. We've reverted to 3.0.2 for one of our libraries.

Thank you very much for this great plugin.

**Comment by simonhaenisch** [comment] 2022-08-31 11:03
Would be really helpful if you could try a patch for me... basically on your Windows machine install the latest version, and then edit `node_modules/prettier-plugin-organize-imports/lib/service-host.js` and remove the if-block here:

https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/2fa075e1624f5b6598b05831eb104fd87b42e47d/lib/service-host.js#L31-L33

Then run Prettier via CLI, or restart your editor if you're running it through the editor (to prevent any caching).

That's how the code used to be before the change, I think, but it's not a correct implementation afaik... anyway, if it works after that change, at least i know where the problem is.

**Comment by blaenk** [comment] 2022-09-01 01:47
Thanks for responding!

I did you one better and set a breakpoint with my debugger. It seems to be a windows path delimiter issue.

```javascript
filePath = "configs/eslint/base/.eslintrc.js"
path = "configs\\eslint\\base\\.eslintrc.js"
```

I suspect there's some way to normalize/canonicalize a path to make them both the same (if they are indeed the same) such as [this](https://nodejs.org/api/path.html#pathnormalizepath) in node.js,, or maybe even some way to directly compare file paths 🤷🏼‍♂️.

Indeed removing the `if` condition made it apply the formatting to the file!

**Comment by simonhaenisch** [comment] 2022-09-01 10:36
Ok cool thanks for that, good job with the debugging 🤓 yeah, I'll figure out how to compare the paths properly with normalized path delimiter.

**Closed** 2022-09-01 10:59 UTC

**Comment by simonhaenisch** [comment] 2022-09-01 11:01
Just published `3.1.1` which should hopefully fix this. Please let me know if it works (:

**Comment by simonhaenisch** [comment] 2022-09-02 09:32
Yup sorry, should work now.

**Comment by blaenk** [comment] 2022-09-02 22:10
That worked! Thank you!
