### ISSUE TITLE
Prettier 3 support

### ISSUE THREAD

**Issue by MarcinBorowski95** [simonhaenisch/prettier-plugin-organize-imports#103] opened 2023-07-20 06:56 UTC
Any chance this plugin will have prettier 3 support update?

**Comment by simonhaenisch** [comment] 2023-07-20 09:14
Duplicate of #95

**Comment by simonhaenisch** [comment] 2023-07-20 09:15
Also, it's right there in the readme: https://github.com/simonhaenisch/prettier-plugin-organize-imports#prettier-3

**Closed by simonhaenisch** 2023-07-20 09:14 UTC

**Comment by MarcinBorowski95** [comment] 2023-07-20 09:49
Sorry, my mistake 😅
